# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertable',
            name='forecast_type',
            field=models.CharField(max_length=15),
        ),
    ]
