# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180328_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathertable',
            options={'get_latest_by': '-loadtime'},
        ),
    ]
