# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180401_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensehattable',
            name='measuretime',
        ),
        migrations.AlterField(
            model_name='sensehattable',
            name='loadtime',
            field=models.CharField(max_length=20),
        ),
    ]
